import {readFile,writeFile} from 'node:fs/promises';
const c=JSON.parse(await readFile('catalog/catalog.json'));
const coverage=c.families.map(f=>{const products=c.products.filter(p=>p.family===f.id),inScope=products.filter(p=>p.inScope),geometric=inScope.filter(p=>p.variants.length);return {id:f.id,name:f.name,status:!inScope.length?'out-of-scope':geometric.length?'partial':'reference-only',products:products.length,withGeometry:geometric.length,variants:products.reduce((n,p)=>n+p.variants.length,0),referenceOnly:products.filter(p=>!p.variants.length).length,limitations:[...new Set(products.map(p=>p.limitations.join(' ')))],source:f.source};});
await writeFile('catalog/coverage.json',JSON.stringify({version:c.version,reviewedAt:c.reviewedAt,families:coverage},null,2)+'\n');
const clean=s=>String(s).replaceAll('|','/').replaceAll('\n',' ');
let report='# Acoperire catalog Decorio\n\nInventar consultat: '+c.reviewedAt+'. Inventarul conține 1077 pagini de produse și modele suplimentare extrase din cataloage. Numărul de variante nu înseamnă număr de sisteme complete de montaj. Toate listele de piese sunt preliminare.\n\n| Familie | Produse | Cu geometrie | Variante | Stare |\n|---|---:|---:|---:|---|\n'+coverage.map(f=>`| [${f.name}](${f.source.url}) | ${f.products} | ${f.withGeometry} | ${f.variants} | ${f.status} |`).join('\n')+'\n';
for(const f of coverage){report+='\n## '+f.name+'\n\n| Produs / sursă | Cod public | Variante | Stare | Limitare |\n|---|---|---:|---|---|\n';report+=c.products.filter(p=>p.family===f.id).map(p=>`| [${clean(p.name)}](${p.source.url}${p.source.page?'#page='+p.source.page:''}) | ${clean(p.sku||'—')} | ${p.variants.length} | ${p.status} | ${clean(p.limitations.join(' '))} |`).join('\n')+'\n';}
await writeFile('docs/catalog-coverage.md',report);
console.log(coverage.length+' families; '+c.products.length+' products; '+c.products.reduce((n,p)=>n+p.variants.length,0)+' variants');
