import {APP_ID,initialState,emptyState,assertState,productVariant,addSegment,moveNode,deleteNode,deleteSegment,changeSegment,setSegmentLength,deriveAssembly,csv,distance} from './model.js';
import {DecorioViewer} from './viewer.js';
import {PlanEditor} from './editor.js';
const $=s=>document.querySelector(s);const option=(value,text)=>{const o=document.createElement('option');o.value=value;o.textContent=text;return o;};
let catalog,state,assembly,viewer,editor,selected='',selectedNode='',history=[],future=[],user=null,cloudReady=false;let toastTimer;
const local=['localhost','127.0.0.1','[::1]'].includes(location.hostname);
const allowed=['decorio.360configurator.ro','decorio.360configurator.com','decorio.360konfigurator.de'];
function notify(message){clearTimeout(toastTimer);$('#toast').textContent=String(message);$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,9000);}
function failure(error){notify(error.message||error);console.warn(error);}
function modal(title,build){$('#dialog-title').textContent=title;$('#dialog-content').replaceChildren();build($('#dialog-content'));if(!$('#dialog').open)$('#dialog').showModal();}
function paragraph(host,text){const p=document.createElement('p');p.textContent=text;host.append(p);return p;}
function download(name,type,text){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function store(){try{localStorage.setItem(APP_ID+':draft',JSON.stringify(state));}catch{notify('Stocarea locală nu este disponibilă. Exportă proiectul JSON pentru a-l păstra.');}}
function commit(next){next=assertState(next,catalog);history.push(structuredClone(state));if(history.length>60)history.shift();future=[];state=next;selected=state.segments.some(e=>e.id===selected)?selected:state.segments[0]?.id||'';refresh();store();}
function selection(){const s={productId:$('#product').value,variantId:$('#variant').value};if(!$('#custom-dimensions').hidden)s.dimensions={width:Number($('#module-width').value),height:Number($('#module-height').value)};return s;}
function renderSizes(){const p=catalog.products.find(p=>p.id===$('#product').value),v=p?.variants.find(v=>v.id===$('#variant').value);$('#custom-dimensions').hidden=!v?.dimensionBounds;if(v?.dimensionBounds){for(const axis of ['width','height']){const el=$('#module-'+axis),b=v.dimensionBounds[axis];el.min=b.min??.1;el.max=b.max;el.value=v[axis];}$('#size-limits').textContent=['width','height'].map((a,i)=>(i?'Înălțime':'Lățime')+': '+(v.dimensionBounds[a].min??'minim nepublicat')+' – '+v.dimensionBounds[a].max+' m').join('; ');}}

function step(name){for(const n of ['catalog','layout','bom'])$('#'+n+'-panel').hidden=n!==name;document.querySelectorAll('[data-step]').forEach(b=>b.classList.toggle('active',b.dataset.step===name));}
function view(mode){$('#viewer').hidden=mode!=='3d';$('#editor').hidden=mode!=='2d';document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===mode));if(mode==='2d')editor.fit(state);}
function renderProducts(){const family=$('#family').value,q=$('#search').value.trim().toLocaleLowerCase('ro'),only=$('#only-configurable').checked,current=$('#product').value;const items=catalog.products.filter(p=>(!family||p.family===family)&&(!only||(p.kind==='panel'&&p.variants.length))&&(!q||(p.name+' '+(p.sku||'')).toLocaleLowerCase('ro').includes(q)));
 $('#product').replaceChildren(...items.map(p=>option(p.id,p.name)));if(items.some(p=>p.id===current))$('#product').value=current;$('#product-count').textContent=items.length+' produse';renderProduct();}
function renderProduct(){const current=$('#variant').value;const p=catalog.products.find(p=>p.id===$('#product').value);$('#variant').replaceChildren();$('#product-specs').replaceChildren(...Object.entries(p?.specifications||{}).flatMap(([k,v])=>{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;return [dt,dd];}));$('#kit-included').replaceChildren();if(p?.variants[0]?.included){paragraph($('#kit-included'),'Incluse în kit (nu se numără separat):');p.variants[0].included.forEach(x=>paragraph($('#kit-included'),x.quantity+' × '+x.name));}$('#product-name').textContent=p?.name||'Niciun produs găsit';$('#product-notes').textContent=p?.limitations.join(' ')||'Încearcă altă familie sau altă căutare.';$('#product-status').textContent=p?.variants.length?'Dimensiuni documentate · montaj de confirmat':'Necesită documentație';$('#product-source').hidden=!p;if(p)$('#product-source').href=p.source.url+(p.source.page?'#page='+p.source.page:'');if(p)$('#variant').replaceChildren(...p.variants.map(v=>option(v.id,v.label)));if(p?.variants.some(v=>v.id===current))$('#variant').value=current;const disabled=!p?.variants.length||p.kind!=='panel';$('#apply-product').disabled=disabled||!selected;$('#draw-product').disabled=disabled;$('#apply-all').disabled=disabled||!state?.segments.length;renderSizes();}
function refresh(){assembly=deriveAssembly(state,catalog);viewer?.render(assembly,state);editor?.render(state,selected,assembly);$('#project-name').value=state.name;$('#total-length').textContent=assembly.totalLength.toFixed(2)+' m';$('#segment-count').textContent=state.segments.length;$('#item-count').textContent=assembly.items.length;$('#undo').disabled=!history.length;$('#redo').disabled=!future.length;$('#dimensions').setAttribute('aria-pressed',state.options.dimensions);$('#segment-select').replaceChildren(...state.segments.map(e=>option(e.id,e.id+' · '+catalog.products.find(p=>p.id===e.productId).name)));$('#segment-select').value=selected;
 const edge=state.segments.find(e=>e.id===selected);$('#segment-length').value=edge?distance(state.nodes.find(n=>n.id===edge.a),state.nodes.find(n=>n.id===edge.b)).toFixed(3):'';$('#set-length').disabled=!edge;$('#delete-segment').disabled=!edge;
 $('#bom-status').textContent=assembly.complete?'Listele sunt complete pentru configurația aleasă.':'Listă preliminară. Include numai componente susținute de documentație; verifică elementele de confirmat.';
 $('#bom-items').replaceChildren(...assembly.items.map(r=>{const d=document.createElement('div');d.className='bom-row';const label=document.createElement('span');label.textContent=r.label;const small=document.createElement('small');small.textContent=r.code?'Cod '+r.code:'Cod comercial de confirmat';label.append(small);const qty=document.createElement('b');qty.textContent=r.quantity+' '+r.unit;d.append(label,qty);return d;}));
 $('#issues').replaceChildren(...assembly.issues.map(i=>{const li=document.createElement('li');li.textContent=(i.segmentId?i.segmentId+': ':'')+i.message;return li;}));renderGates();const enabled=!!$('#variant').value;$('#apply-product').disabled=!enabled||!selected;$('#apply-all').disabled=!enabled||!state.segments.length;
}
function renderGates(){const e=state.segments.find(e=>e.id===selected);const variants=[];if(e){const pv=productVariant(catalog,e.productId,e.variantId).variant;for(const p of catalog.products.filter(p=>p.kind==='gate'&&p.compatibleWith?.includes(e.productId)))for(const v of p.variants)if(v.finish===pv.finish&&Math.abs(v.height-pv.height)<=.100001)variants.push({p,v});}
 $('#gate-product').replaceChildren(...variants.map(({p,v})=>option(p.id+'|'+v.id,p.name+' · '+v.label)));if(!variants.length)$('#gate-product').append(option('','Nicio combinație documentată pentru acest segment'));$('#add-gate').disabled=!variants.length;
 $('#gate-list').replaceChildren(...state.gates.filter(g=>g.segmentId===selected).map(g=>{const b=document.createElement('button');b.textContent='Elimină '+catalog.products.find(p=>p.id===g.productId).name;b.onclick=()=>commit({...structuredClone(state),gates:state.gates.filter(x=>x.id!==g.id)});return b;}));}
function selectSegment(id){selected=id;selectedNode='';$('#node-controls').hidden=true;refresh();}
async function requireCloud(){if(local)throw Error('Salvarea în cont este disponibilă pe domeniul Decorio. Local poți folosi exportul JSON.');if(!cloudReady)throw Error('Tenantul Decorio nu este disponibil. Încearcă din nou după verificarea conexiunii.');if(!user){const auth=await import('../../shared-ui/src/firebaseAuth.js');await auth.signInWithGoogle();}return import('../../shared-ui/src/savedConfigurations.js');}
async function init(){
 if(!local&&!allowed.includes(location.hostname))throw Error('Această instanță este rezervată tenantului Decorio.');
 catalog=await fetch('./catalog.json').then(r=>{if(!r.ok)throw Error('Catalog indisponibil.');return r.json();});
 state=initialState(catalog);
 try{const draft=localStorage.getItem(APP_ID+':draft');if(draft)state=assertState(JSON.parse(draft),catalog);}catch(error){notify('Proiectul local nu a putut fi restaurat: '+error.message);}
 selected=state.segments[0]?.id||'';
 try{viewer=new DecorioViewer($('#viewer'));}catch(e){$('#viewer').textContent='Vizualizarea 3D nu este disponibilă în acest browser. Poți folosi planul 2D.';failure(e);}
 editor=new PlanEditor($('#plan'),{add:(a,b)=>commit(addSegment(state,a,b,selection(),catalog)),move:(id,p)=>commit(moveNode(state,id,p,catalog)),selectSegment,selectNode:id=>{selectedNode=id;const n=state.nodes.find(n=>n.id===id);$('#node-controls').hidden=false;$('#node-x').value=n.x;$('#node-y').value=n.y;},error:failure});
 const familyOrder=catalog.families.filter(f=>catalog.products.some(p=>p.family===f.id&&p.inScope));$('#family').replaceChildren(option('','Toate familiile'),...familyOrder.map(f=>option(f.id,f.name)));
 renderProducts();if(state.segments[0]){$('#product').value=state.segments[0].productId;renderProduct();$('#variant').value=state.segments[0].variantId;}
 refresh();viewer?.fit(state);editor.fit(state);
 if(local){$('#connection-status').textContent='Preview local · export JSON disponibil';$('#login').disabled=true;}else{
  const {resolveTenantContext}=await import('../../shared-ui/src/tenantBootstrap.js');const context=await resolveTenantContext();if(!context?.isTenant||context.slug!=='decorio'||!context.exists||context.status!=='active'||context.configurators?.fence!==true)throw Error('Demo-ul Decorio nu este încă activat. Administratorul platformei trebuie să finalizeze configurarea clientului.');cloudReady=true;$('#connection-status').textContent='Tenant Decorio conectat';
  const auth=await import('../../shared-ui/src/firebaseAuth.js');await auth.observeGoogleAuth(u=>{user=u;$('#login').textContent=u?'Deconectare':'Intră în cont';});
 }
 const params=new URLSearchParams(location.search),hash=new URLSearchParams(location.hash.slice(1));
 if(['s','c','config'].some(key=>params.has(key)||hash.has(key))){
  const {readShareState}=await import('../../shared-ui/src/shareState.js');const shared=await readShareState({productType:'fence'});if(!shared)throw Error('Linkul nu a putut fi restaurat. Proiectul curent a fost păstrat.');commit(assertState(shared,catalog));viewer?.fit(state);
 }
}
function action(id,fn){$(id).addEventListener('click',async()=>{try{await fn();}catch(e){failure(e);}});}
for(const s of ['#family','#only-configurable'])$(s).addEventListener('change',renderProducts);$('#search').addEventListener('input',renderProducts);$('#product').addEventListener('change',renderProduct);
document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>step(b.dataset.step));document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));
$('#variant').addEventListener('change',renderSizes);
action('#apply-all',()=>{const sel=selection(),s=structuredClone(state);s.segments=s.segments.map(e=>{delete e.dimensions;return {...e,...sel};});commit(s);});
action('#apply-product',()=>commit(changeSegment(state,selected,selection(),catalog)));action('#draw-product',()=>{step('layout');view('2d');editor.setMode('draw');});action('#draw',()=>{if(!$('#variant').value)throw Error('Alege mai întâi un produs cu dimensiuni documentate.');view('2d');editor.setMode('draw');});action('#select',()=>editor.setMode('select'));
$('#segment-select').onchange=()=>selectSegment($('#segment-select').value);action('#set-length',()=>commit(setSegmentLength(state,selected,Number($('#segment-length').value),catalog)));action('#delete-segment',()=>commit(deleteSegment(state,selected,catalog)));action('#move-node',()=>commit(moveNode(state,selectedNode,{x:Number($('#node-x').value),y:Number($('#node-y').value)},catalog)));action('#delete-node',()=>{commit(deleteNode(state,selectedNode,catalog));selectedNode='';$('#node-controls').hidden=true;});
action('#add-gate',()=>{const [productId,variantId]=$('#gate-product').value.split('|');const s=structuredClone(state);s.gates.push({id:'g'+crypto.randomUUID().replaceAll('-',''),segmentId:selected,productId,variantId,offset:Number($('#gate-offset').value),handing:$('#gate-hand').value});commit(s);});
action('#undo',()=>{if(history.length){future.push(state);state=history.pop();refresh();store();}});action('#redo',()=>{if(future.length){history.push(state);state=future.pop();refresh();store();}});action('#fit',()=>{viewer?.fit(state);editor.fit(state);});action('#dimensions',()=>commit({...structuredClone(state),options:{dimensions:!state.options.dimensions}}));$('#light').oninput=()=>viewer?.setLight(Number($('#light').value));action('#reset',()=>{commit(emptyState(catalog));editor.setMode('select');});
$('#project-name').onchange=()=>{try{commit({...structuredClone(state),name:$('#project-name').value});}catch(e){failure(e);}};
action('#show-bom',()=>{step('bom');if(innerWidth<741)$('#bom-panel').scrollIntoView({behavior:'smooth'});});action('#export-csv',()=>download('decorio-componente.csv','text/csv;charset=utf-8',csv(assembly,state)));action('#export-json',()=>download('decorio-proiect.json','application/json',JSON.stringify(state,null,2)));
$('#import-json').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>500000)throw Error('Fișierul depășește limita de 500 KB.');const next=assertState(JSON.parse(await file.text()),catalog);commit(next);viewer?.fit(state);editor.fit(state);notify('Proiect importat.');}catch(e){failure(e);}finally{$('#import-json').value='';}};
action('#login',async()=>{const auth=await import('../../shared-ui/src/firebaseAuth.js');if(user)await auth.signOutGoogle();else await auth.signInWithGoogle();});action('#save',async()=>{const api=await requireCloud();await api.saveUserConfiguration({productType:'fence',name:state.name,state});notify('Configurația a fost salvată în contul tău Decorio.');});
action('#share',async()=>{if(local||!cloudReady)throw Error('Distribuirea prin link va fi disponibilă pe domeniul Decorio. Acum poți exporta proiectul JSON.');const {createShareUrl}=await import('../../shared-ui/src/shareState.js');const url=await createShareUrl({productType:'fence',state});modal('Distribuie configurația',host=>{paragraph(host,'Oricine are acest link poate vedea configurația distribuită.');const input=document.createElement('input');input.readOnly=true;input.value=url;host.append(input);input.select();});});
action('#open-projects',async()=>{const api=await requireCloud(),result=await api.listUserConfigurations({productType:'fence'});modal('Proiectele mele',host=>{const items=result;if(!items.length)paragraph(host,'Nu ai încă proiecte salvate în acest tenant.');for(const item of items){const b=document.createElement('button');b.textContent=item.name;b.onclick=async()=>{try{const saved=await api.getUserConfiguration({id:item.id,productType:'fence'});commit(assertState(saved.state||JSON.parse(saved.stateJson),catalog));$('#dialog').close();viewer?.fit(state);}catch(e){failure(e);}};host.append(b);}});});
action('#coverage',()=>modal('Catalog Decorio · acoperire',host=>{paragraph(host,`${catalog.products.length} produse și sisteme inventariate. ${catalog.products.filter(p=>p.variants.length).length} au variante cu dimensiuni documentate. Surse consultate la ${catalog.reviewedAt}. Lista include accesorii și produse în afara fluxului de împrejmuire, marcate separat.`);for(const f of catalog.families){const ps=catalog.products.filter(p=>p.family===f.id),d=document.createElement('div');d.className='coverage-row';const link=document.createElement('a');link.href=f.source.url;link.target='_blank';link.rel='noopener';link.textContent=f.name;const span=document.createElement('span');span.textContent=ps.filter(p=>p.variants.length).length+' cu geometrie / '+ps.length+' inventariate';d.append(link,span);host.append(d);}}));
action('#close-dialog',()=>$('#dialog').close());
init().catch(e=>{failure(e);$('#connection-status').textContent='Conexiune indisponibilă';if(!local&&!cloudReady){document.body.classList.add('blocked');modal('Instanță indisponibilă',host=>paragraph(host,e.message));}});
