import {distance} from './model.js';
const NS='http://www.w3.org/2000/svg';
const el=(tag,attrs={},text='')=>{const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));if(text)e.textContent=text;return e;};
export class PlanEditor{
 constructor(svg,handlers){this.svg=svg;this.handlers=handlers;this.mode='select';this.start=null;this.selected='';this.selectedNode='';this.scale=35;this.origin={x:130,y:180};this.state={nodes:[],segments:[],gates:[]};
  this.width=900;this.height=650;this.resizeObserver=new ResizeObserver(()=>{const r=svg.getBoundingClientRect();if(r.width<1||r.height<1)return;this.width=r.width;this.height=r.height;svg.setAttribute('viewBox',`0 0 ${this.width} ${this.height}`);this.fit(this.state);});this.resizeObserver.observe(svg);
  svg.addEventListener('wheel',e=>{e.preventDefault();this.zoom(e.deltaY>0?1/1.15:1.15);},{passive:false});
  svg.addEventListener('pointerdown',e=>this.down(e));svg.addEventListener('pointermove',e=>this.move(e));svg.addEventListener('pointerup',e=>this.up(e));svg.addEventListener('pointercancel',()=>{this.drag=null;this.render(this.state);});svg.addEventListener('keydown',e=>{if(e.key==='Escape'){this.setMode('select');}});
 }
 zoom(factor){const next=Math.max(8,Math.min(220,this.scale*factor)),f=next/this.scale,cx=this.width/2,cy=this.height/2;this.origin={x:cx+(this.origin.x-cx)*f,y:cy+(this.origin.y-cy)*f};this.scale=next;this.draw(this.state);}
 addNumeric(length,angle){if(!Number.isFinite(length)||length<.1||length>500||!Number.isFinite(angle))throw Error('Lungime sau unghi invalid.');const a=this.start||{x:0,y:0},r=angle*Math.PI/180,b={x:a.x+length*Math.cos(r),y:a.y+length*Math.sin(r)};this.handlers.add(a,b);this.start=b;this.mode='draw';this.handlers.mode?.('draw');this.render(this.state);}
 setMode(mode){this.mode=mode;this.handlers.mode?.(mode);this.svg.focus({preventScroll:true});this.start=null;this.svg.style.cursor=mode==='draw'?'crosshair':mode==='pan'?'grab':'default';this.render(this.state);}
 world(e){const pt=this.svg.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const p=pt.matrixTransform(this.svg.getScreenCTM().inverse());let x=(p.x-this.origin.x)/this.scale,y=(p.y-this.origin.y)/this.scale;
  if(document.querySelector('#snap').checked){x=Math.round(x*10)/10;y=Math.round(y*10)/10;}
  const near=this.state.nodes.find(n=>distance(n,{x,y})*this.scale<12);if(near&&near.id!==this.drag?.id)return {x:near.x,y:near.y};
  if(this.start&&document.querySelector('#ortho').checked){if(Math.abs(x-this.start.x)>Math.abs(y-this.start.y))y=this.start.y;else x=this.start.x;}
  return {x,y};
 }
 screen(n){return {x:this.origin.x+n.x*this.scale,y:this.origin.y+n.y*this.scale};}
 down(e){if(e.button!==0)return;this.svg.focus({preventScroll:true});e.preventDefault();const node=e.target.dataset.node,segment=e.target.dataset.segment;
  if(this.mode==='pan'){this.pan={x:e.clientX,y:e.clientY,origin:{...this.origin}};this.svg.setPointerCapture(e.pointerId);return;}
  if(this.mode==='draw'){const point=node?{x:this.state.nodes.find(n=>n.id===node).x,y:this.state.nodes.find(n=>n.id===node).y}:this.world(e);if(!this.start){this.start=point;this.render(this.state);}else{const first=this.start;try{this.handlers.add(first,point);this.start=point;}catch(err){this.handlers.error(err);}this.render(this.state);}return;}
  if(node){this.selectedNode=node;this.handlers.selectNode(node);this.drag={id:node,point:this.world(e),moved:false};this.svg.setPointerCapture(e.pointerId);}
  else if(segment){this.selected=segment;this.selectedNode='';this.handlers.selectSegment(segment);this.render(this.state);}
 }
 move(e){if(this.pan){const r=this.svg.getBoundingClientRect(),ratio=Math.max(this.width/r.width,this.height/r.height);this.origin={x:this.pan.origin.x+(e.clientX-this.pan.x)*ratio,y:this.pan.origin.y+(e.clientY-this.pan.y)*ratio};this.draw(this.state);return;}if(this.drag){this.drag.point=this.world(e);this.drag.moved=true;const temp=structuredClone(this.state);Object.assign(temp.nodes.find(n=>n.id===this.drag.id),this.drag.point);this.draw(temp);}else if(this.mode==='draw'&&this.start){this.draw(this.state);const a=this.screen(this.start),b=this.screen(this.world(e));const world=this.world(e),length=distance(this.start,world),angle=Math.atan2(world.y-this.start.y,world.x-this.start.x)*180/Math.PI;this.handlers.preview?.(length,angle);this.svg.append(el('text',{x:(a.x+b.x)/2,y:(a.y+b.y)/2-10,'text-anchor':'middle',fill:'#8e6423'},length.toFixed(2)+' m · '+angle.toFixed(0)+'°'));this.svg.append(el('circle',{cx:b.x,cy:b.y,r:6,fill:'none',stroke:'#b58d3a'}));this.svg.append(el('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:'#b58d3a','stroke-width':2,'stroke-dasharray':'6 5'}));}}
 up(e){if(this.pan){this.pan=null;if(this.svg.hasPointerCapture(e.pointerId))this.svg.releasePointerCapture(e.pointerId);return;}if(!this.drag)return;const d=this.drag;this.drag=null;if(this.svg.hasPointerCapture(e.pointerId))this.svg.releasePointerCapture(e.pointerId);if(d.moved)try{this.handlers.move(d.id,d.point);}catch(err){this.handlers.error(err);}this.render(this.state);}
 fit(state){if(!state.nodes.length){this.scale=35;this.origin={x:this.width*.25,y:this.height*.45};this.render(state);return;}const xs=state.nodes.map(n=>n.x),ys=state.nodes.map(n=>n.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);this.scale=Math.min(65,Math.max(100,this.width-100)/Math.max(5,maxX-minX),Math.max(70,this.height-240)/Math.max(4,maxY-minY));this.origin={x:this.width/2-(minX+maxX)/2*this.scale,y:this.height/2-(minY+maxY)/2*this.scale};this.render(state);}
 render(state,selected=this.selected,assembly){if(assembly){this.gateParts=assembly.parts.filter(p=>p.kind==='gate');this.parts=assembly.parts;}if(this.start&&this.state.nodes.some(n=>distance(n,this.start)<.001)&&!state.nodes.some(n=>distance(n,this.start)<.001))this.start=null;this.state=state;this.selected=selected;this.draw(state);}
 draw(state){const s=this.svg;s.replaceChildren();const defs=el('defs'),pattern=el('pattern',{id:'grid',width:this.scale,height:this.scale,patternUnits:'userSpaceOnUse',x:this.origin.x%this.scale,y:this.origin.y%this.scale});pattern.append(el('path',{d:`M ${this.scale} 0 L 0 0 0 ${this.scale}`,fill:'none',stroke:'#d8dfd1','stroke-width':.7}));defs.append(pattern);s.append(defs,el('rect',{width:this.width,height:this.height,fill:'url(#grid)'}));
  const nodes=new Map(state.nodes.map(n=>[n.id,n]));for(const e of state.segments){const a=this.screen(nodes.get(e.a)),b=this.screen(nodes.get(e.b));s.append(el('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,class:'hit','data-segment':e.id}),el('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,class:'edge'+(this.selected===e.id?' selected':''),'data-segment':e.id}));s.append(el('text',{x:(a.x+b.x)/2,y:(a.y+b.y)/2-12,'text-anchor':'middle',fill:'#466146'},e.id+' · '+distance(nodes.get(e.a),nodes.get(e.b)).toFixed(2)+' m'));}
  for(const part of this.parts||[]){if(!['panel','gap'].includes(part.kind))continue;const a=this.screen(part.a),b=this.screen(part.b),angle=Math.atan2(b.y-a.y,b.x-a.x),dx=-Math.sin(angle)*5,dy=Math.cos(angle)*5;s.append(el('line',{x1:a.x+dx,y1:a.y+dy,x2:b.x+dx,y2:b.y+dy,stroke:part.kind==='gap'?'#b56440':'#a0b7af','stroke-width':part.kind==='gap'?3:5,'stroke-dasharray':part.kind==='gap'?'5 5':'none','pointer-events':'none'}));}
  for(const gate of this.gateParts||[]){
   const a=this.screen(gate.a),b=this.screen(gate.b),angle=Math.atan2(b.y-a.y,b.x-a.x),r=gate.variant.width*this.scale,sign=gate.handing==='left'?1:-1,end={x:a.x-Math.sin(angle)*r*sign,y:a.y+Math.cos(angle)*r*sign};
   s.append(el('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:'#fafbf6','stroke-width':9}),el('line',{x1:a.x,y1:a.y,x2:end.x,y2:end.y,stroke:'#ad8131','stroke-width':3}),el('path',{d:`M ${a.x+Math.cos(angle)*r} ${a.y+Math.sin(angle)*r} A ${r} ${r} 0 0 ${sign===1?1:0} ${end.x} ${end.y}`,fill:'none',stroke:'#ad8131','stroke-dasharray':'4 3'}));
  }
  for(const n of state.nodes){const p=this.screen(n);s.append(el('circle',{cx:p.x,cy:p.y,r:7,class:'node'+(this.selectedNode===n.id?' selected':''),'data-node':n.id}));s.append(el('text',{x:p.x+12,y:p.y+18,fill:'#76836d'},n.id));}
  if(this.start){const p=this.screen(this.start);s.append(el('circle',{cx:p.x,cy:p.y,r:10,fill:'none',stroke:'#ba913b','stroke-width':2}));}
 }
}
